export const staticData = [{
  id: `${Date.now()}1`,
  name: 'Sahil Dua',
  like: false,
  created_at: new Date(),
  description: 'Some random description 1....',
  imageColor: 'green',
},{
  id: `${Date.now()}2`,
  name: 'Sahil Dua',
  like: false,
  created_at: new Date(),
  description: 'Some random description 2....',
  imageColor: 'yellow',
},{
  id: `${Date.now()}3`,
  name: 'Sahil Dua',
  like: false,
  created_at: new Date(),
  description: 'Some random description 3....',
  imageColor: 'blue',
},{
  id: `${Date.now()}4`,
  name: 'Sahil Dua',
  like: false,
  created_at: new Date(),
  description: 'Some random description 4....',
  imageColor: 'red',
},{
  id: `${Date.now()}5`,
  name: 'Sahil Dua',
  like: false,
  created_at: new Date(),
  description: 'Some random description 5....',
  imageColor: 'pink',
},{
  id: `${Date.now()}6`,
  name: 'Sahil Dua',
  like: false,
  created_at: new Date(),
  description: 'Some random description 6....',
  imageColor: 'orange',
},{
  id: `${Date.now()}7`,
  name: 'Sahil Dua',
  like: false,
  created_at: new Date(),
  description: 'Some random description 7....',
  imageColor: 'black',
},{
  id: `${Date.now()}8`,
  name: 'Sahil Dua',
  like: false,
  created_at: new Date(),
  description: 'Some random description 8....',
  imageColor: 'brown',
},{
  id: `${Date.now()}9`,
  name: 'Sahil Dua',
  like: false,
  created_at: new Date(),
  description: 'Some random description 9....',
  imageColor: 'maroon',
},{
  id: `${Date.now()}10`,
  name: 'Sahil Dua',
  like: false,
  created_at: new Date(),
  description: 'Some random description 10....',
  imageColor: 'grey',
}];